import Head from "next/head";
import { Grid } from "@mui/material";
export default function HomeP() {
  return (
    <Grid component="main">
      <Head>
        <title>Myopia 👨‍⚕️ : Practitioner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Grid>
  );
}
